---
title: "CBA Final Project"
author: "Liv & Madi"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(kableExtra)
library(scales)
```

```{r}
# load data
property <- read.csv(here::here("data", "property spreadsheet.csv")) %>% 
  janitor::clean_names() %>% 
  drop_na(market_value_2015)
```

```{r}
# set factors
property$parcel_number <- as.factor(property$parcel_number)
property$use_description <- as.factor(property$use_description)
property$pool_spa <- as.factor(property$pool_spa)
property$in_floodplain <- as.factor(property$in_floodplain)

# convert year_built to years_old
property <- property %>% 
  mutate(years_old = 2024 - year_built)
```


```{r}
# visualize data
hist(property$distance_to_wetland)

hist(property$market_value_2024)

#take the log of the market value to make it more normal
hist(log(property$market_value_2024))

hist(property$market_value_2015)

#log of 2015 market value
hist(log(property$market_value_2015))

hist(property$net_assessed_value)
```

```{r}
# look at means
property %>% 
  group_by(in_floodplain) %>% 
  summarize(mean_2024 = mean(market_value_2024),
            mean_2015 = mean(market_value_2015),
            mean_assessed = mean(net_assessed_value),
            mean_dist = mean(distance_to_wetland))

# Was it in the floodplain before the open space restoration? 
# 0 = yes, 1 = no
# hypothesis: house values in the floodplain would be lower pre-restoration and about similar post-restoration
# result: houses that were in the floodplain were more expensive in 2015 and in 2024 (but is this difference significant?)
```

```{r}
# run linear regression
reg1 <- lm(market_value_2024 ~ acreage + area_square_feet + years_old + number_bedrooms + number_bathrooms + number_fireplaces + garage + pool_spa + distance_to_wetland + in_floodplain,
          data = property)
summary(reg1)


#histogram of residuals
plot(reg1)
hist(reg1$residuals)
```

```{r}
# run linear regression
reg2 <- lm(market_value_2015 ~ acreage + area_square_feet + years_old + number_bedrooms + number_bathrooms + number_fireplaces + garage + pool_spa + distance_to_wetland + in_floodplain,
          data = property)
summary(reg2)

#histogram of residuals
plot(reg2)
hist(reg2$residuals)
```

```{r}
# run linear regression
reg3 <- lm(net_assessed_value ~ acreage + area_square_feet + years_old + number_bedrooms + number_bathrooms + number_fireplaces + garage + pool_spa + distance_to_wetland + in_floodplain,
          data = property)
summary(reg3)

#histogram of residuals
plot(reg3)
hist(reg3$residuals)
```


```{r}
# Extract summary stats for reg1
reg1_summary <- broom::tidy(reg1) %>%
  # Round the values for better presentation
  mutate(
    estimate = round(estimate, 2),
    std.error = round(std.error, 2),
    statistic = round(statistic, 2),
    p.value = round(p.value, 3)
  )

# Export as csv
write_csv(reg1_summary, here::here("reg1_summary.csv"))

# Extract summary stats for reg2
reg2_summary <- broom::tidy(reg2) %>%
  # Round the values for better presentation
  mutate(
    estimate = round(estimate, 2),
    std.error = round(std.error, 2),
    statistic = round(statistic, 2),
    p.value = round(p.value, 3)
  )

# Export as csv
write_csv(reg2_summary, here::here("reg2_summary.csv"))

# Extract summary stats for reg3
reg3_summary <- broom::tidy(reg3) %>%
  # Round the values for better presentation
  mutate(
    estimate = round(estimate, 2),
    std.error = round(std.error, 2),
    statistic = round(statistic, 2),
    p.value = round(p.value, 3)
  )

# Export as csv
write_csv(reg3_summary, here::here("reg3_summary.csv"))

```

# Bar Graph

```{r}
property_long <- property %>%
  pivot_longer(
    cols = starts_with("market_value"),
    names_to = "year",
    names_prefix = "market_value_",
    values_to = "market_value"
  )
```

```{r}
property_long %>%
  group_by(in_floodplain, year) %>%
  summarize(
    mean_value = mean(market_value, na.rm = TRUE),
    sd_value = sd(market_value, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = year, y = mean_value, fill = in_floodplain)) +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  geom_errorbar(
    aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value),
    position = position_dodge(0.9),
    width = 0.2
  ) +
  labs(
    x = "Year",
    y = "Mean Market Value (dollars)",
    fill = "Previously in Floodplain"
  ) +
  scale_fill_manual(
    values = c("0" = "#00BFFF", "1" = "#FFA500"),
    labels = c("0" = "Yes (n = 24)", "1" = "No (n = 20)")
  ) +
  scale_y_continuous(labels = label_comma()) + 
  theme_minimal()

#save it 6x5
ggsave(here::here("mean_market_value_by_year_and_floodplain.png"))


```

